import { Raleway, Cabin } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  variable: "--font-family-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const cabin = Cabin({
  variable: "--font-family-cabin",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${cabin.variable}`}>
        {children}
      </body>
    </html>
  );
}
